apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
    iam.gke.io/gcp-service-account: task2-gke-service-account@bustling-winter-323317.iam.gserviceaccount.com
  name: gke-service-account